-- MySQL Script generated by MySQL Workbench
-- Sat Dec 23 19:39:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `idprofessor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idprofessor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materia` (
  `idmateria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nivel_dificuldade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nivel_dificuldade` (
  `idnivel_dificuldade` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idnivel_dificuldade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questao` (
  `idquestao` INT NOT NULL AUTO_INCREMENT,
  `pergunta` VARCHAR(500) NOT NULL,
  `resposta_correta` VARCHAR(500) NOT NULL,
  `resposta_errada1` VARCHAR(500) NOT NULL,
  `resposta_errada2` VARCHAR(500) NOT NULL,
  `resposta_errada3` VARCHAR(500) NOT NULL,
  `resposta_erradar4` VARCHAR(500) NOT NULL,
  `imagem` LONGBLOB NOT NULL,
  `materia` INT NOT NULL,
  `questaocol` VARCHAR(45) NOT NULL,
  `questaocol1` VARCHAR(45) NOT NULL,
  `dificuldade` INT NOT NULL,
  PRIMARY KEY (`idquestao`),
  INDEX `fk_mateira_idx` (`materia` ASC),
  INDEX `fk_dificuldade_idx` (`dificuldade` ASC),
  CONSTRAINT `fk_materia`
    FOREIGN KEY (`materia`)
    REFERENCES `mydb`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dificuldade`
    FOREIGN KEY (`dificuldade`)
    REFERENCES `mydb`.`nivel_dificuldade` (`idnivel_dificuldade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`serie` (
  `idserie` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idserie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `idaluno` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `serie` INT NOT NULL,
  PRIMARY KEY (`idaluno`, `serie`),
  INDEX `fk_serie_idx` (`serie` ASC),
  CONSTRAINT `fk_serie`
    FOREIGN KEY (`serie`)
    REFERENCES `mydb`.`serie` (`idserie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno_responde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno_responde` (
  `idaluno_responde` INT NOT NULL AUTO_INCREMENT,
  `aluno` INT NULL,
  `questao` INT NULL,
  `correto` CHAR(1) NULL,
  PRIMARY KEY (`idaluno_responde`),
  INDEX `fk_aluno_idx` (`aluno` ASC),
  INDEX `fk_questao_idx` (`questao` ASC),
  CONSTRAINT `fk_aluno`
    FOREIGN KEY (`aluno`)
    REFERENCES `mydb`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questao`
    FOREIGN KEY (`questao`)
    REFERENCES `mydb`.`questao` (`idquestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor_ensina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor_ensina` (
  `idprofessor_ensina` INT NOT NULL AUTO_INCREMENT,
  `professor` INT NOT NULL,
  `materia` INT NOT NULL,
  `serie` INT NOT NULL,
  PRIMARY KEY (`idprofessor_ensina`),
  INDEX `fk_professor_idx` (`professor` ASC),
  INDEX `fk_materia_idx` (`materia` ASC),
  INDEX `fk_serie_idx` (`serie` ASC),
  CONSTRAINT `fk_professor`
    FOREIGN KEY (`professor`)
    REFERENCES `mydb`.`professor` (`idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia`
    FOREIGN KEY (`materia`)
    REFERENCES `mydb`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serie`
    FOREIGN KEY (`serie`)
    REFERENCES `mydb`.`serie` (`idserie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
